services:
  app:
    image: todo-frontend-dev
    build:
      context: ./todo-app/todo-frontend
      dockerfile: Dockerfile.dev
    ports:
      - "5173:5173"
    volumes:
      - ./todo-app/todo-frontend:/usr/src/app
      - /usr/src/app/node_modules
    environment:
      - VITE_BACKEND_URL=http://localhost:3000

  server:
    image: todo-backend
    build:
      context: ./todo-app/todo-backend
    ports:
      - "3000:3000"
    environment:
      - MONGO_URL=mongodb://mongo:27017/todo-db
    depends_on:
      - mongo

  mongo:
    image: mongo
    volumes:
      - mongo-data:/data/db

volumes:
  mongo-data: